

#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int lightValue; //declaring variables
	int darkValue;
	int sumValue;
	int thresholdValue;

	int countValue = 0;
	int lastSeen;
	int count2=0;
	nMotorPIDSpeedCtrl[motorA] = mtrSpeedReg; //ensuring that the motors are moving at same speed
	nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;

	darkValue=47; 
	lightValue=79;
	sumValue = lightValue + darkValue;
	thresholdValue = sumValue/2; // determining threshold value
	wait1Msec(2000);
	clearTimer(T1);

	lastSeen = 1;

	while(count2 <3){

	while (countValue < 9)//entering while loop, determining when to turn
	{
		if (SensorValue(lightSensor) > thresholdValue) //initate movement 
		{
			 motor[motorA]=30;
			 motor[motorB]=30;


			 if (lastSeen == 1)
			 {
				 countValue = countValue + 1;
				 lastSeen = 0;
				displayString(25, "%d", countValue);
			 }
		}//exiting while loop

		else
		 {
			lastSeen = 1;
			displayString(25, "%d", countValue);
		 }

	}//end while


	     motor[motorA]=30; //turning on the gride 
			 motor[motorB]=-30;
			 wait1Msec(600);

			  motor[motorA]=30;
			 motor[motorB]=30;
			 wait1Msec(1100);

			 motor[motorA]=30;
			 motor[motorB]=-30;
			 wait1Msec(500);

			 countValue = 0;


	while (countValue < 9)
	{
		if (SensorValue(lightSensor) > thresholdValue) //intiating movement after first turn
		{
			 motor[motorA]=30;
			 motor[motorB]=30;


			 if (lastSeen == 1)
			 {
				 countValue = countValue + 1;
				 lastSeen = 0;
				displayString(25, "%d", countValue);
			 }
		}

		else
		 {
			lastSeen = 1;
			displayString(25, "%d", countValue);
		 }


	}//end while

	     motor[motorA]=-30;
			 motor[motorB]=30;
			 wait1Msec(600);

			  motor[motorA]=30;
			 motor[motorB]=30;
			 wait1Msec(1100);

			 motor[motorA]=-30;
			 motor[motorB]=30;
			 wait1Msec(500);
			 countValue =0;
			 count2++;
}
	while (countValue < 9) //until it reaches edge this code is performed
	{
		if (SensorValue(lightSensor) > thresholdValue)
		{
			 motor[motorA]=30;
			 motor[motorB]=30;


			 if (lastSeen == 1)
			 {
				 countValue = countValue + 1;
				 lastSeen = 0;
				displayString(25, "%d", countValue);
			 }
		}
		else
		 {
			lastSeen = 1;
			displayString(25, "%d", countValue);
		 }
	}//end while


			 countValue=0;

			 while (countValue < 9) //until it reaches edge this code is performed
	{
		if (SensorValue(lightSensor) > thresholdValue)
		{
			 motor[motorA]=-30;
			 motor[motorB]=-30;


			 if (lastSeen == 1)
			 {
				 countValue = countValue + 1;
				 lastSeen = 0;
				displayString(25, "%d", countValue);
			 }
		}
		else
		 {
			lastSeen = 1;
			displayString(25, "%d", countValue);
		 }
	}//end while



			 /*
			 if (SensorValue(lightSensor) < thresholdValue)
			 {


		   }

		   if (SensorValue(lightSensor) < // 200mecs )
		   {
		   black_box ++

		   }
		   void testData()
			{
				string fileName = "testFile.txt";
				short N = 2000; //number of bytes to write
			 	TFileHandle fp;
				TFileIOResult result;
				OpenWrite(fp, result, fileName, N);

			  string string1 = "Line 1 \n";
			  string string2 = "Line 2 \n";
			  string string3 = "Cathy Test";

			  WriteText(fp, result, string1);
			  WriteText(fp, result, string2);
			  WriteText(fp, result, string3);

			  // Close the file, this automatically flushes the
			  // buffers to the "disk".
			  Close(fp, result);

			}




			 */








}
